-- MySQL Script generated by MySQL Workbench
-- 04/24/17 18:08:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL,
  `building_name` VARCHAR(45) NULL,
  `building_number` INT NULL,
  `street_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` INT NULL,
  `hours` DATETIME NULL,
  `UID_access` TINYINT(1) NULL,
  `campus` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`multipurpose_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`multipurpose_rooms` (
  `location_id` INT NOT NULL,
  `multipurpose_rooms_id` VARCHAR(45) NOT NULL,
  INDEX `fk_rooms_location1_idx` (`location_id` ASC),
  PRIMARY KEY (`multipurpose_rooms_id`),
  CONSTRAINT `fk_rooms_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_items` (
  `multipurpose_room_items_id` INT NOT NULL,
  `room_number` VARCHAR(45) NULL,
  `room_name` VARCHAR(45) NULL,
  `rent_availability` TINYINT(1) NULL,
  `rent_range` VARCHAR(45) NULL,
  `multipurpose_rooms_multipurpose_rooms_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`multipurpose_room_items_id`),
  INDEX `fk_room_items_multipurpose_rooms1_idx` (`multipurpose_rooms_multipurpose_rooms_id` ASC),
  CONSTRAINT `fk_room_items_multipurpose_rooms1`
    FOREIGN KEY (`multipurpose_rooms_multipurpose_rooms_id`)
    REFERENCES `mydb`.`multipurpose_rooms` (`multipurpose_rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`library` (
  `library_id` INT NOT NULL AUTO_INCREMENT,
  `library_name` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`library_id`),
  INDEX `fk_library_location_idx` (`location_id` ASC),
  CONSTRAINT `fk_library_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`space_descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`space_descriptions` (
  `space_descriptions_id` INT NOT NULL,
  `book_rental` VARCHAR(45) NULL,
  `room_rental` VARCHAR(45) NULL,
  `tech_rental` VARCHAR(45) NULL,
  `loud_quiet_space` VARCHAR(45) NULL,
  `group_ind_space` VARCHAR(45) NULL,
  `printing` VARCHAR(45) NULL,
  `seating_type` VARCHAR(45) NULL,
  `library_id` INT NOT NULL,
  `study_space_id` VARCHAR(45) NULL,
  `multipurpose_rooms_multipurpose_rooms_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`space_descriptions_id`),
  INDEX `fk_space_descriptions_library1_idx` (`library_id` ASC),
  INDEX `fk_space_descriptions_multipurpose_rooms1_idx` (`multipurpose_rooms_multipurpose_rooms_id` ASC),
  CONSTRAINT `fk_space_descriptions_library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `mydb`.`library` (`library_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_space_descriptions_multipurpose_rooms1`
    FOREIGN KEY (`multipurpose_rooms_multipurpose_rooms_id`)
    REFERENCES `mydb`.`multipurpose_rooms` (`multipurpose_rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`study_space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`study_space` (
  `study_space_id` INT NOT NULL,
  INDEX `fk_study_space_space_descriptions1_idx` (`study_space_id` ASC),
  CONSTRAINT `fk_study_space_space_descriptions1`
    FOREIGN KEY (`study_space_id`)
    REFERENCES `mydb`.`space_descriptions` (`study_space_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_study_space_location1`
    FOREIGN KEY (`study_space_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`academic_dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`academic_dept` (
  `academic_dept_id` INT NOT NULL,
  `dept_name` VARCHAR(45) NULL,
  `dept_hours` TIME NULL,
  `dept_number` INT NULL,
  `dept_email` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`academic_dept_id`),
  INDEX `fk_academic_dept_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_academic_dept_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_org`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_org` (
  `student_org_id` INT NOT NULL,
  `org_name` VARCHAR(45) NULL,
  `org_email` VARCHAR(45) NULL,
  PRIMARY KEY (`student_org_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `events_id` INT NOT NULL,
  `event_name` VARCHAR(45) NULL,
  `event_date` DATE NULL,
  `event_time` TIME NULL,
  `academic_dept_id` INT NOT NULL,
  `student_org_student_org_id` INT NOT NULL,
  PRIMARY KEY (`events_id`),
  INDEX `fk_events_academic_dept1_idx` (`academic_dept_id` ASC),
  INDEX `fk_events_student_org1_idx` (`student_org_student_org_id` ASC),
  CONSTRAINT `fk_events_academic_dept1`
    FOREIGN KEY (`academic_dept_id`)
    REFERENCES `mydb`.`academic_dept` (`academic_dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_student_org1`
    FOREIGN KEY (`student_org_student_org_id`)
    REFERENCES `mydb`.`student_org` (`student_org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`computer_labs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`computer_labs` (
  `idcomputer_labs` INT NOT NULL,
  PRIMARY KEY (`idcomputer_labs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dining_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dining_area` (
  `dining_area_id` INT NOT NULL,
  `area_name` VARCHAR(45) NULL,
  `area_hours` DATETIME NULL,
  `food_type` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`dining_area_id`),
  INDEX `fk_dining_area_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_dining_area_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
